export const GET_MAIN_MATERIALS_SUCCESS = 'GET_MAIN_MATERIALS_SUCCESS'
export const GET_MAIN_MATERIALS_FAILED = 'GET_MAIN_MATERIALS_FAILED'

export const INIT_PRODUCTS = 'INIT_PRODUCTS'
export const INIT_PRODUCT = 'INIT_PRODUCT'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED'

export const INIT_BAG_ITEMS = 'INIT_BAG_ITEMS'
export const SET_BAG_ITEMS_SUCCESS = 'SET_BAG_ITEMS_SUCCESS'
export const SET_BAG_ITEMS_FAILED = 'SET_BAG_ITEMS_FAILED'
export const CLEAN_BAG_SUCCESS = 'CLEAN_BAG_SUCCESS'
