export const GET_MAIN_MATERIALS_SUCCESS = 'GET_MAIN_MATERIALS_SUCCESS'
export const GET_MAIN_MATERIALS_FAILED = 'GET_MAIN_MATERIALS_FAILED'

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED'
